---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: self-security-flux-kustom
  namespace: default
spec:
  interval: 30m0s
  path: ./k8s-infra
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: self-security-flux-source
  targetNamespace: default
  timeout: 3m0s
  wait: true
